// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbTM8iL39gyxP-JimuyYrEExdmJPgXDa8',
    appId: '1:59298191114:web:0226d8c39a97f36dd8ccf3',
    messagingSenderId: '59298191114',
    projectId: 'rideshare-f7a89',
    authDomain: 'rideshare-f7a89.firebaseapp.com',
    storageBucket: 'rideshare-f7a89.appspot.com',
    measurementId: 'G-9Q5EYG27NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYOqmTXNlNVUwiPQBx8o38ufz5i2KLkVQ',
    appId: '1:59298191114:android:f060b9002f06b5cad8ccf3',
    messagingSenderId: '59298191114',
    projectId: 'rideshare-f7a89',
    storageBucket: 'rideshare-f7a89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd6jLCJ8ZT6ot07lWUKYYm1YTCxtWRPFg',
    appId: '1:59298191114:ios:ec55160ab64f2477d8ccf3',
    messagingSenderId: '59298191114',
    projectId: 'rideshare-f7a89',
    storageBucket: 'rideshare-f7a89.appspot.com',
    iosBundleId: 'com.example.rideShareTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd6jLCJ8ZT6ot07lWUKYYm1YTCxtWRPFg',
    appId: '1:59298191114:ios:ec55160ab64f2477d8ccf3',
    messagingSenderId: '59298191114',
    projectId: 'rideshare-f7a89',
    storageBucket: 'rideshare-f7a89.appspot.com',
    iosBundleId: 'com.example.rideShareTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbTM8iL39gyxP-JimuyYrEExdmJPgXDa8',
    appId: '1:59298191114:web:cdb66ce84c2f8460d8ccf3',
    messagingSenderId: '59298191114',
    projectId: 'rideshare-f7a89',
    authDomain: 'rideshare-f7a89.firebaseapp.com',
    storageBucket: 'rideshare-f7a89.appspot.com',
    measurementId: 'G-R2J57VS5P8',
  );

}